on:
  push:
    branches:
      - main

env: 
  DOCTAVE_VERSION: "0.4.1"
  DOCTAVE_TAR_GZ: doctave-${{ env.DOCTAVE_VERSION }}-x86_64-unknown-linux-musl.tar.gz

jobs:
  doctave:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: install doctave
        run: |
          wget https://github.com/Doctave/doctave/releases/download/${{ env.DOCTAVE_VERSION }}/${{ env.DOCTAVE_TAR_GZ }}
          tar xvf ${{ env.DOCTAVE_TAR_GZ }}
      - name: doctave build && mv
        working-directory: main
        run: |
          doctave build --release
          rm -rf ../gh-pages/*
          mv site/* ../gh-pages/
      - name: git commit && git push
        working-directory: gh-pages
        run: |
          git add .
          git commit -m "build(main): ${{ github.sha }}"
          git push
